-- AlterTable
ALTER TABLE `optometrichistory` MODIFY `ocular_conditions` VARCHAR(191) NULL,
    MODIFY `family_history` VARCHAR(191) NULL,
    MODIFY `visual_acuity_left` VARCHAR(191) NULL,
    MODIFY `visual_acuity_right` VARCHAR(191) NULL,
    MODIFY `refraction_left` VARCHAR(191) NULL,
    MODIFY `refraction_right` VARCHAR(191) NULL,
    MODIFY `intraocular_pressure` VARCHAR(191) NULL,
    MODIFY `slit_lamp_exam` VARCHAR(191) NULL,
    MODIFY `fundoscopy` VARCHAR(191) NULL,
    MODIFY `diagnosis` VARCHAR(191) NULL,
    MODIFY `treatment_plan` VARCHAR(191) NULL,
    MODIFY `visual_field_test` VARCHAR(191) NULL,
    MODIFY `color_vision_test` VARCHAR(191) NULL,
    MODIFY `corneal_topography` VARCHAR(191) NULL,
    MODIFY `anterior_segment` VARCHAR(191) NULL,
    MODIFY `posterior_segment` VARCHAR(191) NULL,
    MODIFY `other_notes` VARCHAR(191) NULL;
